apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: tp4
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080